{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odi.postgres.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odi.labels" . | nindent 4 }}
# CloudNativePG uses kubernetes.io/basic-auth secrets for bootstrapping.
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
