apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odi.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odi.labels" . | nindent 4 }}
type: Opaque
stringData:
  opensearch-password: {{ include "odi.opensearchPassword" . | quote }}
  zefix-dsn: {{ include "odi.zefixDSN" . | quote }}
  {{- if eq .Values.backend.storage.type "b2" }}
  b2-account: {{ .Values.backend.storage.b2.account | quote }}
  b2-key: {{ .Values.backend.storage.b2.key | quote }}
  b2-bucket-name: {{ .Values.backend.storage.b2.bucketName | quote }}
  b2-passphrase: {{ .Values.backend.storage.b2.passphrase | quote }}
  {{- end }}
